### PR TITLE
Set order currency in variant autocomplete

### PR DESCRIPTION
**Pull request by sherryson**
allows admin users to add items to existing subscriptions based on the last completed orders currency.

an item unavailable for purchase in a store/currency cannot be added by an admin to a subscription

i started to add a spec for the method i added to the subscription model but it was pretty painful, and i didn't feel that it was really adding anything. lmk if you think i need to add a corresponding spec though.

### CODE REVIEW

**Review by hugobast — APPROVED** [review]
Looooooks goooood. @mickeyren can you see why the Travis build is failing on a method missing, I looked (not a hard look) but couldn't see a reason out of this PR that makes it fail.

**Comment by sherryson** [comment]
@hugobast @mickeyren aghh i can't figure out why the travis build keeps failing in the rake execution. i don't have any problems locally running the specs... can i get a hand with this?

**Comment by papayaah** [comment]
i think it's going to pass now - after i restarted the job too...

**Comment by papayaah** [comment]
@sherryson your branch is outdated with `v2` - i merged `v2` to your branch.

**Comment by sherryson** [comment]
@hugobast @mickeyren are we good to merge this into v2 then and open a gem bump pr in glossier-v2?

**Comment by papayaah** [comment]
LGTM, we should also merge my PR so we only need to bump the v2 gem once.

**Pull request merged**
